###############################################################################
#                          Generated on phpdocker.io                          #
###############################################################################
version: "3.1"
services:

    mysql:
      image: mysql:5.7
      container_name: haarlem-festival-mysql
      working_dir: /application
      volumes:
        - .:/application
        - ./mysql:/var/lib/mysql
      environment:
        - MYSQL_ROOT_PASSWORD=rootpw
        - MYSQL_DATABASE=haarlemdb
        - MYSQL_USER=dbuser
        - MYSQL_PASSWORD=userpw
      ports:
        - "3306:3306"

        
    webserver:
      image: nginx:alpine
      container_name: haarlem-festival-webserver
      working_dir: /application
      volumes:
          - .:/application
          - ./phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      ports:
       - "6789:80"

    php-fpm:
      build: phpdocker/php-fpm
      container_name: haarlem-festival-php-fpm
      working_dir: /application
      volumes:
        - .:/application
        - ./phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/7.3/fpm/conf.d/99-overrides.ini

